warnings_are_errors: false
language: r
cache: packages
sudo: false
services:
  - mysql
before_script:
  - mysql -u root -e 'CREATE DATABASE travistorrent;'
  - mysql -u root travistorrent < database/test.sql
r_packages:
  - devtools
  - testthat
r_github_packages:
  - hadley/devtools
  - hadley/testthat
