warnings_are_errors: false
language: r
cache: packages
sudo: false
env:
  global:
    - CRAN: http://cran.rstudio.com
services:
  - mysql
before_script:
  - mysql -u root -e 'CREATE DATABASE travistorrent;'
  - mysql -u root travistorrent < database/new_data.sql 
r_packages:
  - devtools
  - testthat
r_github_packages:
  - hadley/devtools
  - hadley/testthat
  
r_binary_packages:
  - RMySQL
