warnings_are_errors: false
language: r
cache: packages
sudo: false
services:
  - mysql
before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS travistorrent;" -uroot
before_script:
  - mysql -u root -e 'CREATE DATABASE testbase;'
  - mysql -u root testbase < database/test.sql
r_packages:
  - devtools
  - testthat
r_github_packages:
  - hadley/devtools
  - hadley/testthat
