warnings_are_errors: false
language: r
cache: packages
sudo: false
services:
  - mysql
before_script:
  - mysql -u root -e 'CREATE DATABASE travistorrent;'
  - mysql -u root travistorrent < database/new_data.sql 
r_packages:
  - devtools
  - testthat
  - RMySQL
r_github_packages:
  - hadley/devtools
  - hadley/testthat
  - rstats-db/RMySQL

