warnings_are_errors: false
language: r
cache: packages
sudo: false
services:
  - mysql
before_install:
  - mysql -e "CREATE DATABASE IF NOT EXISTS travistorrent;" -uroot
install:
  - ./travis-tool.sh github_package hadley/testthat
