#load and install all packages
#install.packages("corrplot")
#install.packages("devtools")
#install.packages("testthat")
#install.packages("RMySQL")
#install.packages("qtlcharts")
#install.packages("rpart")
#install.packages("mlbench")
#install.packages("caret")
#install.packages("randomForest")


#library(devtools)
#library(testthat)
#library(RMySQL)
#library('corrplot')
#library('qtlcharts')
#library(rpart)
#library(mlbench)
#library(caret)
#library(randomForest)